### ISSUE TITLE
issues with position of note and struct function

### ISSUE THREAD

**Issue by larkob** [tidalcycles/strudel#154] opened 2022-07-15 08:02 UTC
I'm wondering if this is a bug or by design:

`s("bd") .struct("x x x x") .out()` plays all beats
`note("a2 b2 c3 d3 e3 f3 g3@2")  .s("piano") .out()` plays all notes
but 
`struct("x x x x") .s("bd") .out()` gives an error
`s("piano") .note("a2 b2 c3 d3 e3 f3 g3@2") .out()` plays the first note only

**Comment by yaxu** [comment] 2022-07-15 08:15
`struct` is a function that structures one pattern with the events of another, i.e. it needs two inputs. by calling it on another pattern like `s("bd") .struct("x x x x")` you give it that second input. It might be possible to support `struct("x x x x") .s("bd")` but I think that could be a bit confusing.

There are a range of different ways to combine two patterns, but the default used in `s("piano") .note("a2 b2 c3 d3 e3 f3 g3@2")` is to structure the result according to the rhythm given by the pattern on the left. It's the equivalent of `s("piano").setIn(note("a2 b2 c3 d3 e3 f3 g3@2")) .out()` - a method that sets values in to the structure of the pattern it's called on. `s("piano").setOut(note("a2 b2 c3 d3 e3 f3 g3@2")) .out()` does the opposite.

**Comment by felixroos** [comment] 2022-07-15 08:15
By design, the (temporal) structure comes from the left, so `s("piano") .note("a2 b2 c3 d3 e3 f3 g3@2") .out()` will take `s("piano")` as structure (only one event). You might find [this comment](https://github.com/tidalcycles/strudel/discussions/82#discussioncomment-2625112) helpful to understand that. 

To flip the structure, we started to implementing `xOut` functions, so in this case `s("piano") .noteOut("a2 b2 c3 d3 e3 f3 g3@2") .out()` would theoretically be the thing to use, but `noteOut` is not implemented / generated yet. 

`struct("x x x x") .s("bd") .out()` gives an error because struct only exists as a method and not as a function, probably we could add it as a function too, but I am not sure how it would work.

Btw you can also use mini notation inside s, so you won't need the struct: `s("bd bd bd bd").out()` or `s("bd*4").out()`

I'll close this, as it is kind of duplicate with the above mentioned discussion

**Closed by felixroos** 2022-07-15 08:15 UTC

**Comment by yaxu** [comment] 2022-07-15 08:19
I'm not sure if I'd thought of implementing 'noteOut' and friends yet, it's a good idea! Would it be a problem having so many methods? I guess we could find out..

Maybe it's better to have this kind of discussion here: https://club.tidalcycles.org/c/strudel/26

Then we can embed examples.
